### ISSUE TITLE
Illegal string offset 'class' - get this after adding widget to Yii2 gridview

### ISSUE THREAD

**Issue by dustyghost** [kartik-v/yii2-datecontrol#101]
Hi,

Having a small issue adding the datecontrol widget to a gridview.
Here is my code in the index file:

`GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

```
        //'id',
        'entryNumber',
        'categoryId',
        //'accountId',
        'description',
        'amount',
        //'account.description',
         //'displayEntryDate',
         //'entryDate',
        [
            'attribute' => 'entryDate',
            'value' => 'entryDate',
            'filter' => DateControl::widget(DateControl::classname(), ['type'=>DateControl::FORMAT_DATE,])
        ],
        ['class' => 'yii\grid\ActionColumn'],
    ],
]);`
```

When I run this I get the following error:
PHP Warning – yii\base\ErrorException
Illegal string offset 'class'
![error](https://cloud.githubusercontent.com/assets/10135321/17466181/cf5f69da-5d01-11e6-940e-0fb5d991c5c9.jpg)

**Comment by Enrica-r** [comment]
I think your column option title is wrong. Here is my working example:

```php
     ['attribute' => 'rcv_out_date', 'format' => 'date', 'width' => '10%',
           'filterType' => '\kartik\datecontrol\DateControl',
     ],
```` 
Type of 'FORMAT_DATE' is chosen automatically. Please try and provide feedback.
