### ISSUE TITLE
Setting unknown property: kartik\date\DatePicker::aria-required

### ISSUE THREAD

**Issue by serhatozles** [kartik-v/yii2-datecontrol#103]
I updated my composer just now. and getting this error. 
not working like following that;
```
<?= $form->field($model, 'finish_date')->widget(DateControl::classname(), [
                        'type' => DateControl::FORMAT_DATE,
                        'displayFormat' => 'dd/MM/yyyy',
                        'options' => [
                            'pluginOptions' => [
                                'id' => 'finish_date',
                                'autoclose' => true,
                                'todayHighlight' => true,
                                'todayBtn' => true,
                                'startDate' => "d",
                            ],
                            'layout' => '{picker}{input}',
                        ],
                    ]) ?>
```

working like that;
`<?= $form->field($model, 'finish_date')->widget(DateControl::classname(), []) ?>`

What's wrong that? That's working normally before update?

**Comment by serhatozles** [comment]
https://github.com/yiisoft/yii2/issues/13140

**Comment by cebe** [comment]
should be reopened, see https://github.com/yiisoft/yii2/issues/13140#issuecomment-265310854

**Comment by kartik-v** [comment]
Refer new property `widgetOptions` that will now need to be used (BC breaking) and is updated in [the usage section of the docs](http://demos.krajee.com/datecontrol#usage).
