### ISSUE TITLE
Always displaying 12:30 on update

### ISSUE THREAD

**Issue by adrianquevada15** [kartik-v/yii2-datecontrol#109]
I am using a DateControl widget by Kartik in my Yii2-powered system. The widget correctly saves the time I've selected. However, when I tried to update the data, it just always shows "12:30" as the time and not the saved time from the database. I am still new to Yii2 and I there's not much information on the Internet regarding this issue. Thank you for the help!

**Comment by kartik-v** [comment]
Check your `saveFormat` matches exactly the format in which your data is saved and as usual look at the other configurations as well like `saveTimezone` and `displayTimezone` and `displayFormat`.

**Comment by adrianquevada15** [comment]
I have no issues with my saveformat. It saves the correct time (e.g. 6:30 PM is saving as 18:30:00 in my database). My problem is, I need to display 6:30 PM as I update the record. However, as I said, it always displays 12:30. Thank you so much sir.

**Comment by adrianquevada15** [comment]
I found the solution. I just understand what you really mean Mr. Kartik. The `displaySettings` should be `hh:mm a ` and not `HH:mm a`. The format should really match.
