### ISSUE TITLE
CSS conflict with bootstrap 4

### ISSUE THREAD

**Issue by bSushil** [kartik-v/yii2-datecontrol#116]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of yii2-datecontrol.
- [ ] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/datecontrol) and [demo](http://demos.krajee.com/datecontrol-demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Implement bootstrap 4.
2. Implement datecontrol widget

The css of bootstrap 4 is destroyed after using datecontrol widget.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

#### Browsers

- [X] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-datecontrol version:

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/datecontrol-demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-datecontrol without other plugins.

**Comment by kartik-v** [comment]
Update to latest release for Bootstrap 4.x support.
