### ISSUE TITLE
DateControl widget not playing nice with Select2 widget

### ISSUE THREAD

**Issue by maz0717** [kartik-v/yii2-datecontrol#119]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-datecontrol.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/datecontrol) and [demo](http://demos.krajee.com/datecontrol-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [x] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Place a Select2 widget on the same page as DateControl widgets.
2. Choose dates, then select something using the select2 widget
3.

## Expected behavior and actual behavior

When I follow those steps, I see the date control widget not passing dates to the server.  Though the dates are still shown correctly on the page.

I was expecting the datecontrol widget fields to pass the selected dates to the server.

#### Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [x] Windows
- [x] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version: v3.2.1
- yii2-datecontrol version: latest

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/datecontrol-demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-datecontrol without other plugins.

**Comment by maz0717** [comment]
Here is my form:
`<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\datecontrol\DateControl;
use kartik\select2\Select2;

?>

<?php $form = ActiveForm::begin(['method' => 'get']) ?>

    <div class="container-fluid">
        <div class="row">
            <?= $form->field($model, 'partner',[
                ])->widget(Select2::classname(), [
                    'data' => $partnerList,
                    'options' => ['placeholder' => 'Search for a partner ...', 'multiple' => false],
                    'pluginOptions' => [
                        'allowClear' => true,
                        // 'minimumInputLength' => 3,
                    ],
                ]
            ); ?>
        </div>
        <div class="row">
            <?= $form->field($model,'order_status')->dropDownList($orderStatusList); ?>
        </div>
        <div class="row">
            <?= $form->field($model,'order_date_start')->widget(DateControl::classname(),[
                'type' => 'date'
            ]); ?>
        </div>
        <div class="row">
            <?= $form->field($model,'order_date_end')->widget(DateControl::classname(),[
                'type' => 'date'
            ]); ?>
        </div>
    </div>

    <?= Html::submitButton() ?>

<?php ActiveForm::end() ?>

**Comment by kartik-v** [comment]
Please check for javascript errors on your browser console and see if its related to some JS error.

**Comment by maz0717** [comment]
No javascript errors.  And it seems to be an intermittent problem.  There is also a problem with date control losing when going back to the form via the browser back button.  To clarify.  There are various circumstances in which the date control loses the date.  I have been able to produce the lost results by hard refreshing the form, selecting dates, then selecting partner which is a Select2 widget.  But it only happens sometimes.  I'll continue to investigate.    Any help or pointers would be appreciated.
