### ISSUE TITLE
Does not convert the date into timestamp.

### ISSUE THREAD

**Issue by slo-nik** [kartik-v/yii2-datecontrol#122]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of yii2-datecontrol.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/datecontrol) and [demo](http://demos.krajee.com/datecontrol-demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. update from yii2 2.0.12  to  2.0.13.1 and above
2. in config file "language" => "ru"
3. settings in config file
```php
'datecontrol' =>  [
            'class' => '\kartik\datecontrol\Module',
            'displaySettings' => [
                Module::FORMAT_DATE => 'd MMMM yyyy',
                Module::FORMAT_TIME => 'HH:mm',
                Module::FORMAT_DATETIME => 'd MMMM yyyy HH:mm'
            ],
            'displayTimezone' => 'Europe/Kiev',
            'autoWidgetSettings' => [
                Module::FORMAT_DATETIME => ['pluginOptions' => [
                    'autoclose' => true,
                    'todayHighlight' => true,
                    'startDate' => date('d m Y'),
                ],
                    'readonly' => true],
                Module::FORMAT_DATE => ['pluginOptions' => [
                    'autoclose' => true,
                    'todayHighlight' => true,
                    //'startDate' => date('d m Y'),
                ],
                    'readonly' => true],
                Module::FORMAT_TIME => ['readonly' => true]
            ],
            'saveSettings' => [
                Module::FORMAT_DATETIME => 'php:U',
                Module::FORMAT_DATE => 'php:U',
                Module::FORMAT_TIME => 'php:U',
            ],
            'ajaxConversion' => true,
        ]
```
composer.json
```json
     "kartik-v/yii2-datecontrol": "dev-master",
```
composer.lock
````json
      "name": "kartik-v/yii2-datecontrol",
      "version": "dev-master",
````
## Expected behavior and actual behavior

When I follow those steps, I see empty "value"
```html
    <input id="date" name="Article[date]" value="" type="hidden">
```
and empty "output" in the server response
```javascript
    {"status":"success","output":""}
```

I expected the server's response to the value for the "output" in timestamp format
```javascript
    {"status":"success","output":"1518904800"}
```
```html
 <input id="date" name="Article[date]" value="1518904800" type="hidden">
```

#### Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

#### Libraries

- jQuery version: 3.2.1
- yii2-datecontrol version: dev-master

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/datecontrol-demo)
- [ ] The bug happens consistently across all tested browsers
- [x] This bug happens when using yii2-datecontrol without other plugins.

**Comment by educationisenemy** [comment]
ParseController does not load options from request
@slo-nik you probably use dev-master, try to use v1.9.6 until master will be fixed
