### ISSUE TITLE
Timezone ignored when use FORMAT_DATE

### ISSUE THREAD

**Issue by gelid** [kartik-v/yii2-datecontrol#126]
## Steps to reproduce the issue

**in config module**
```
'displayTimezone' => 'Europe/Moscow',
'saveTimezone' => 'UTC',
```

**in config widget**
```
'name' => 'birthday',
'type'=>DateControl::FORMAT_DATE,
'value' => $profile->birthday,
'widgetOptions' => [
	'pluginOptions' => [
		'autoclose' => true
	]
],
'displayFormat' => 'php: d/m/Y',
'saveFormat' => 'php:U',
```

**in config yii formatter** 
```
'defaultTimeZone' => 'Europe/Moscow',
'timeZone' => 'GMT+3',
```

**in php timezone** Europe/Moscow

**in db mysql** field birthday (int 11)

When I follow those steps, I see

in output php function date('d.m.Y' $birthday) has 24.03.2018
in output widget has 23.03.2018

in core/vendor/kartik-v/yii2-datecontrol/DateControl.php on line 369
```
// skip timezone validations when using date only inputs
if ($this->type === self::FORMAT_DATE) {
   $this->displayTimezone = $this->saveTimezone = null;
}
```

if i comment this rule - has in vidget 24.03.2018 - right date

can i use FORMAT_DATE with timezone anyway else?

**Comment by gwebnick** [comment]
У меня такая же проблема, дата уменьшается на 1 день.
В логах указано:
2018-07-17 16:58:27 [127.0.0.1][-][paieg0dlrsiinihu71klspu263][error][yii\base\UnknownPropertyException] yii\base\UnknownPropertyException: Setting unknown property: kartik\date\DatePicker::displayTimezone in E:\OSPanel\domains\yii.loc\vendor\yiisoft\yii2\base\Component.php:209
Stack trace:
#0 E:\OSPanel\domains\yii.loc\vendor\yiisoft\yii2\BaseYii.php(546): yii\base\Component->__set('displayTimezone', 'Europe/Moscow')

**Comment by gwebnick** [comment]
Конфиг приложения у меня такой:
`<?php

use kartik\datecontrol\Module as DateControl;
use kartik\date\DatePicker;

return [
    'language' => 'ru-RU',
    'timeZone' => 'Europe/Moscow',
    'aliases' => [
        '@bower' => '@vendor/bower-asset',
        '@npm'   => '@vendor/npm-asset',
    ],
    'vendorPath' => dirname(dirname(__DIR__)) . '/vendor',
    'components' => [
        'cache' => [
            'class' => 'yii\caching\FileCache',
        ],
        'formatter' => [
            'class' => 'yii\i18n\Formatter',
            'decimalSeparator' => ',',
            'thousandSeparator' => ' ',
            'currencyCode' => 'RUR',
            'dateFormat' => 'dd.MM.yyyy',
            'timeFormat' => 'HH:mm:ss',
            'datetimeFormat' => 'dd.MM.yyyy HH:mm:ss',
        ],
    ],
    'modules' => [
        'datecontrol' =>  [
            'class' => 'kartik\datecontrol\Module',

            // format settings for displaying each date attribute (ICU format example)
            'displaySettings' => [
                DateControl::FORMAT_DATE => 'dd.MM.yyyy',
                DateControl::FORMAT_TIME => 'HH:mm:ss',
                DateControl::FORMAT_DATETIME => 'dd.MM.yyyy HH:mm:ss',
            ],

            // format settings for saving each date attribute (PHP format example)
            'saveSettings' => [
                DateControl::FORMAT_DATE => 'php:U',
                DateControl::FORMAT_TIME => 'php:U',
                DateControl::FORMAT_DATETIME => 'php:U',
            ],

            // use ajax conversion for processing dates from display format to save format
            'ajaxConversion' => true,

            // set your display timezone
            'displayTimezone' => 'Europe/Moscow',

            // set your timezone for date saved to db
            'saveTimezone' => 'UTC',

            // automatically use kartik\widgets for each of the above formats
            'autoWidget' => true,

            // default settings for each widget from kartik\widgets used when autoWidget is true
            'autoWidgetSettings' => [
                DateControl::FORMAT_DATE => [
                    'type'=> DatePicker::TYPE_COMPONENT_APPEND,
                    'pluginOptions'=> ['autoclose' => true],
                ],
                DateControl::FORMAT_DATETIME => [
                    'type'=> DatePicker::TYPE_COMPONENT_APPEND,
                    'pluginOptions'=> ['autoclose' => true],
                ],
                DateControl::FORMAT_TIME => [
                    'type'=> DatePicker::TYPE_COMPONENT_APPEND,
                    'pluginOptions'=> ['autoclose' => true],
                ],
            ],
        ],
    ],
];
`
Вызываю виджет в шаблоне так:
`<?= $form->field($model, 'birth_date')->widget(DateControl::className()) ?>`

**Comment by kartik-v** [comment]
@gelid use the `FORMAT_DATETIME` instead of `FORMAT_DATE` if you need to validate timezones

```php
'name' => 'birthday',
'type'=>DateControl::FORMAT_DATE,
'value' => $profile->birthday,
'widgetOptions' => [
	'pluginOptions' => [
		'autoclose' => true
	]
],
'displayFormat' => 'php: d/m/Y',
'saveFormat' => 'php:U',
```

**Comment by chaimleich** [comment]
@kartik-v  Using `FORMAT_DATETIME` is not always a viable solution. I'm using the `DateControl` for a field that must be displayed only as a date, and I'm having the same issue: in `config/web.php`, but timezones are configured to 'Asia/Jerusalem', the timestamp saves correctly according to this timezone, but when I try to edit the record, the date is **displayed** incorrectly.

What is the logic of ignoring the timezone for date-only values? Perhaps the `DateControl` can support a boolean flag that decides whether or not to ignore the timezone when using `FORMAT_DATE`?

**Comment by kartik-v** [comment]
Using the configuration example I shared above will always display it as a date and save as a date.

I will need to still understand this right... because there have been various undesirable effects reported in the past on timezone conversion for dates (do a search on issues for timezone with date format)

Primarily after a lot of deliberations there is a discussion on this in issue #96 and a #102 and a final fix #110 (you had other issues in the past like #72).

Open to suggestions.

**Comment by chaimleich** [comment]
Thank you @kartik-v for the detailed and quick reply! I'm beginning to understand the complication. We'll try your solution and see if it suits our use case.

**Comment by VaNnOrus** [comment]
> 
> 
> @gelid use the `FORMAT_DATETIME` instead of `FORMAT_DATE` if you need to validate timezones
> 
> ```
> 'name' => 'birthday',
> 'type'=>DateControl::FORMAT_DATETIME,
> 'value' => $profile->birthday,
> 'widgetOptions' => [
> 	'pluginOptions' => [
> 		'autoclose' => true
> 	]
> ],
> 'displayFormat' => 'php: d/m/Y',
> 'saveFormat' => 'php:U',
> ```

@kartik-v but if use the "FORMAT_DATETIME" for widget it needs to pick up TIME after DATE were pick up. What to do if that field need only for set DATE? // sorry if my english too bad 

@gwebnick блин, я с проблемой отображения даты в виджете уже полгода маюсь, думал это я туплю :rofl:

**Comment by le0m** [comment]
@VaNnOrus you can hide the TIME part with `minView` option ;)
```
'widgetOptions' => [
   'pluginOptions' => [
     'minView' => 'month'
  ]
]
```

**Comment by VaNnOrus** [comment]
@le0m @kartik-v oh, thanx for help, now I will use that. 
But anyway ignore timezone in `FORMAT_DATE` is a very strange behavior for the format, imho

**Comment by le0m** [comment]
Sorry to resurrect this, but using the approach mentioned above **did not work in the end**.

With this config:
```
'type'=>DateControl::FORMAT_DATETIME,
'widgetOptions' => [
	'pluginOptions' => [
		'autoclose' => true
	]
],
'displayFormat' => 'php: d/m/Y H:i:s',
'saveFormat' => 'php:U',
```

selecting a date actually shows that the timezone is preserved (i live in GMT+1 and shows 01:00:00 in the time section).

This is the reason #96 and #102 lead to the approach mentioned above (see #110).

I finally **reverted** to using a basic config for date-only and time-only inputs:
```
'type' => DateControl::FORMAT_DATE,
'widgetOptions' => [
	'pluginOptions' => [
		'autoclose' => true
	]
],
```

and setting my `Yii::$app->timeZone` to UTC, while my `Yii::$app->formatter->timeZone` is set from an user's attribute.

The only **problem** with this is that `Yii::$app->formatter` still applies user's timezone to dates, so if I'm displaying a `DetailView` or using the formatter in general, I have to override it to provide myself the desired behavior (to use `Yii::$app->timeZone` instead of `Yii::$app->formatter->timeZone` when the format is date-only or time-only).
