### ISSUE TITLE
Disable input by js method doesn't work

### ISSUE THREAD

**Issue by tmendesilva** [kartik-v/yii2-datecontrol#129]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-datecontrol.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/datecontrol) and [demo](http://demos.krajee.com/datecontrol-demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [x] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

Bug reproduced on demo page

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

#### Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-datecontrol version: last one (bs3 demo page)

## Isolating the problem

- [x] This bug happens [on the demos page](https://demos.krajee.com/datecontrol-demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-datecontrol without other plugins.

```
echo $form->field($model, 'when')->widget(DateControl::class, [
                        'type' => DateControl::FORMAT_DATETIME,
                        'displayFormat' => 'dd/MM/yyyy H:i',
                        'saveFormat' => 'dd-MM-yyyy H:i',
                        'ajaxConversion' => false,
                        'widgetOptions' => [
                            'size' => 'sm',
                            'options' => ['class' => 'datetimepicker'],
                        ]
                    ]);
```

> When disable input using $('#demo-datetime_1-disp').prop('disabled', true) input is disabled, but the pickerButton still works and date change. **Happens on DateControl::FORMAT_DATETIME type only**.

![Screenshot from 2019-05-08 21-07-43](https://user-images.githubusercontent.com/9949531/57416258-d65e7c80-71d5-11e9-9f81-9e402e00d334.png)

**Comment by kartik-v** [comment]
That's because you are Just disabling input without reinitalizing the datepicker plugin. If you are modifying through javascript you need to reinitialize the plugin with all updated options and config.

**Comment by tmendesilva** [comment]
How can I do it using this extension?

**Comment by devaptas** [comment]
Some tip about how to re-enable a Datecontrol (FORMAT_DATETIME) input without destroy it?
