### ISSUE TITLE
DateControl with Datetime Widget fails if TYPE_INLINE is set

### ISSUE THREAD

**Issue by ItsReddi** [kartik-v/yii2-datecontrol#136]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-datecontrol.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/datecontrol) and [demo](http://demos.krajee.com/datecontrol-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. 
```php
echo DateControl::widget([
    'name'=>'kartik-date-1',
    'type'=>DateControl::FORMAT_DATETIME,
    'widgetClass' => DateTimePicker::class,
    'widgetOptions' => [
        'type' => DateTimePicker::TYPE_INLINE
    ],
]);
```
After selecting a date time the input field contains malformed date and time
![grafik](https://user-images.githubusercontent.com/3147888/92487934-344a0c80-f1ee-11ea-8efe-d39122d57821.png)

## Expected behavior
Should work like normal DateTimePicker.

```php
echo DateTimePicker::widget([
    'name' => 'kartik-date-2',
    'pluginOptions' => []
]);
```
![grafik](https://user-images.githubusercontent.com/3147888/92488326-ae7a9100-f1ee-11ea-97fc-2f5f61bf6f30.png)

OR

```php
echo DateTimePicker::widget([
    'name' => 'datetime_10',
    'pluginOptions' => [],
    'type' => DateTimePicker::TYPE_INLINE
]);
```
![grafik](https://user-images.githubusercontent.com/3147888/92488862-60b25880-f1ef-11ea-87f2-a22cbf5205cc.png)

DateControl without type inline works also:
```php
echo DateControl::widget([
    'name'=>'kartik-date-1',
    'type'=>DateControl::FORMAT_DATETIME,
    'widgetClass' => DateTimePicker::class,
    'widgetOptions' => [
       // 'type' => DateTimePicker::TYPE_INLINE
    ],
]);
```

![grafik](https://user-images.githubusercontent.com/3147888/92489130-b25ae300-f1ef-11ea-8674-32390336625b.png)

#### Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- yii2-datecontrol version: v1.9.7

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/datecontrol-demo)
No since there is no configuration like that
- [x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-datecontrol without other plugins.

**Comment by kartik-v** [comment]
What are your date format settings?

**Comment by ItsReddi** [comment]
Set via params:
Output before widget:
```
["dateControlDisplay"]=>
  array(3) {
    ["date"]=>
    string(10) "dd.MM.yyyy"
    ["time"]=>
    string(5) "HH:mm"
    ["datetime"]=>
    string(16) "dd.MM.yyyy HH:mm"
  }
```

**Comment by ItsReddi** [comment]
It seems that it has something to do with `pluginOptions['linkFormat']`

###TYPE_INLINE (in parseDateFormat on return)
![grafik](https://user-images.githubusercontent.com/3147888/92563005-2ee4d480-f277-11ea-9a42-595e43cbbe52.png)

if we add:
`$this->pluginOptions['linkFormat'] = $this->pluginOptions['format'];`
right before return, it seems to work correctly. Did not try any other formats now, just removed all custom config.

**Comment by ItsReddi** [comment]
not stale, just not released yet, only merged in master without version

**Comment by ItsReddi** [comment]
@kartik-v could you release the master, so we are able to require a non dev version again?

**Comment by ItsReddi** [comment]
not stale, just not released yet, only merged in master without version
