### ISSUE TITLE
Set the date value?

### ISSUE THREAD

**Issue by nsanden** [kartik-v/yii2-datecontrol#17]
Hey buddy. Continuing to enjoy using these great widgets. 

Should this work? It worked at one time... My date input box is empty however with this code.

``` php
        use kartik\datecontrol\DateControl;
        // Use a DateTimePicker input with ActiveForm and model validation enabled.
        $model->start_date = '2014-08-20';
        echo $form->field($model, 'start_date')
            ->widget(DateControl::classname(), [
            'type'=>DateControl::FORMAT_DATE
        ]);
```

**Comment by DiegoRodriguezTandil** [comment]
Hi, 

I'm working with https://github.com/kartik-v/yii2-datecontrol to format the display and save format. The domain of database field is TimeStamp.
The select and the save date are working fine, but when update the previous value is not shown.
The code is 
`        echo Form::widget([
                'model'=>$model,
                'form'=>$form,
                'columns'=>2,
                'attributes'=>[       // 2 column layout
                    'fechaEntrada'=>[
                        'type'=>Form::INPUT_WIDGET, 
                        'widgetClass'=>'kartik\datecontrol\DateControl', 
                        'hint'=>'Ingrese Fecha de Alta (dd/mm/yyyy)',
                    ],
                    'fechaBaja'=>[
                        'type'=>Form::INPUT_WIDGET, 
                        'widgetClass'=>'kartik\datecontrol\DateControl', 
                        'hint'=>'Ingrese Fecha de Baja (dd/mm/yyyy)'
                    ],
                   ]
            ]);
`

**Comment by atonKin86** [comment]
Got similar problem because of MariaDB timestamp field. DB field type is timestamp BUT it stores data in mysql date format. With DateControl save format php:U i got sql error of dateformat, with DateControl save format php:Y-m-d i got empty value (blank field) in ActiveForm same as nsanden.
