### ISSUE TITLE
Wrong capitalization in 'autoClose'

### ISSUE THREAD

**Issue by marqu3s** [kartik-v/yii2-datecontrol#37]
Hi.
In this url https://github.com/kartik-v/yii2-datecontrol I can see that in this line
Module::FORMAT_DATE => ['type'=>2, 'pluginOptions'=>['autoclose'=>true]], // example
autoclose is written with a lower case 'c'.

But in this url http://demos.krajee.com/datecontrol it still shows with an upper case 'C'.
Module::FORMAT_DATE => ['type'=>2, 'pluginOptions'=>['autoClose'=>true]], // example

Thus auto close of the date picker dialog doesn't work until I changed it to a lower case 'c' since I copied it from the example on the demo page.

**Comment by kartik-v** [comment]
Fixed in docs.
