### ISSUE TITLE
Calculating the date on the web page

### ISSUE THREAD

**Issue by pvlg** [kartik-v/yii2-datecontrol#38]
Hello,
I think it would be nice to pass timezone offset to a page view, and then calculate the date. Instead of calculating the date of Ajax requests.

**Comment by kartik-v** [comment]
There is a reason for Ajax conversions. Javascript does not understand Yii's i18n formats or PHP Date Format settings - and hence this cannot be standardized unless you create a complete library of i18n Format conversions and timezone databases in javascript (that would be a huge repo and not something one would want to maintain for simple date conversion).

For simpler conversions (if you do not need timezone or complex i18n) - there is a feasibility in this extension to do without ajax. You can set `ajaxConversion` to `false`, and the plugin internally uses Krajee's php-date-formatter.js plugin to format PHP date time formats in Javascript for display and convert them back to PHP Date time format on save.
