### ISSUE TITLE
Add input event

### ISSUE THREAD

**Issue by pvlg** [kartik-v/yii2-datecontrol#39]
The problem is that when you press the submit event does not fire if the field does not lose focus and eventually the date does not change.
Why not add "input" event?
 
           $el.on('change', function () {
                if (isEmpty($el.val())) {
                    $idSave.val('');
                } else {

            $el.on('change input', function () {
                if (isEmpty($el.val())) {
                    $idSave.val('');
                } else {

**Comment by kartik-v** [comment]
Not desired since this will trigger an ajax request on every keypress.

I am enhancing the plugin a bit for you to call a new `validate` method manually for any such use cases - for example you could call this on button click and then trigger form submit.
