### ISSUE TITLE
Saved date value is always 1 day behind

### ISSUE THREAD

**Issue by RGTimothy** [kartik-v/yii2-datecontrol#40]
For example if I choose 11-01-2015 (dd-mm-yyyy) on the calendar and submit it, i will get "10-01-2015" in my database. Why is that?

**Comment by kartik-v** [comment]
It seems to be a timezone error. Set your `displayTimezone` and `saveTimezone` correctly.

**Comment by RGTimothy** [comment]
nice! i should have been set its saveTimezone to my widget. These code was all i need :
<pre>
<?php   

    $form = ActiveForm::begin(['type'=>ActiveForm::TYPE_HORIZONTAL]); echo Form::widget([

    'model' => $model,
    'form' => $form,
    'columns' => 1,
    'attributes' => [

//'follow_up_date'=>['type'=> Form::INPUT_TEXT, 'options'=>['placeholder'=>'Enter Follow Up Date...', 'maxlength'=>50]], 

'followed_up_by_id'=>['type'=> Form::INPUT_TEXT, 'options'=>['placeholder'=>'Enter Followed Up By ID...', 'readonly'=>true, 'value'=>Yii::$app->user->id]], 

'scheduled_date'=>['type'=> Form::INPUT_WIDGET, 'widgetClass'=>DateControl::classname(), 'options'=>['type'=>DateControl::FORMAT_DATE, 'saveTimezone'=>Yii::$app->modules['datecontrol']['displayTimezone']]], 
...
</pre>
