### ISSUE TITLE
Call to undefined method kartik\base\Config::initModule()

### ISSUE THREAD

**Issue by p4scu41** [kartik-v/yii2-datecontrol#44]
I am getting this error: Call to undefined method kartik\base\Config::initModule(). I followed the documentation, but I don't know what is my error

![error](https://cloud.githubusercontent.com/assets/1633236/6134285/c82c373a-b125-11e4-80fe-41e73c7ac28e.png)

**Comment by kartik-v** [comment]
You have outdated packages. Update to latest release via composer.
