### ISSUE TITLE
Invalid Configuration

### ISSUE THREAD

**Issue by sredXNY** [kartik-v/yii2-datecontrol#46]
Hi everyone, I'm using datecontrol Module, I configured it in console.php just like is defined in https://github.com/kartik-v/yii2-datecontrol#module
 In the form I have this:
$form->field($model, 'Fecha_fin')->widget(DateControl::classname(), [
				'type'=>DateControl::FORMAT_DATE,
				'ajaxConversion'=>false,
				'options' => [
					'pluginOptions' => [
						'autoclose' => true
					]
				]
		]);

but when I run it I have the next error: "The 'datecontrol' module MUST be setup in your Yii configuration file and must be an instance of 'kartik\datecontrol\Module'."
In what 'm failing?thanks!

**Comment by kartik-v** [comment]
You must define the modules in the right Yii Application configuration file. You are wrongly defining it in `console.php`.

For example you could set in `frontend\config\main.php` for yii advanced app OR `config\web.php` for basic app.

**Comment by kmolina09** [comment]
how do I have to configure the module in yii2 advanced
I have this in my _form.php
use kartik\datecontrol\DateControl;
use kartik\datecontrol\Module;


<?= $form->field($model, 'fecha_resolucion')->widget(DateControl::classname(), [
        'displayFormat' => 'dd/MM/yyyy',
        'autoWidget' => false
    ]);
    ?>

and when I run my controller I get the following error 
Invalid Configuration – yii\base\InvalidConfigException

The 'datecontrol' module MUST be setup in your Yii configuration file and must be an instance of 'kartik\datecontrol\Module'.

where is where I have to put this

The extension has been created as a module to enable access to global settings for your application. In addition, it allows you to read and format date times between client and server using PHP DateTime object. The DateControl widget uses ajax processing to convert display (view) format to model (save) format.

use kartik\datecontrol\Module;
'modules' => [
'datecontrol' =>  [
        'class' => 'kartik\datecontrol\Module',

        // format settings for displaying each date attribute (ICU format example)
        'displaySettings' => [
            Module::FORMAT_DATE => 'dd-MM-yyyy',
            Module::FORMAT_TIME => 'HH:mm:ss a',
            Module::FORMAT_DATETIME => 'dd-MM-yyyy HH:mm:ss a', 
        ],

do I have to put it in 
mysite\backend\config\main.php  ?
or 
mysite\common\config\main.pgp or params.php ??


Thanks in advance!

**Comment by paskuale75** [comment]
strange attitude, I configure it as module in @common/config/main.php but apache log return me exception, don't see the module :( why ? In other repo it work fine !!

**Comment by psad73** [comment]
just in case, for yii2-advanced , put the module configuration into _config/main-local.php_. If you don't want to place _use kartik\datecontrol\Module;_ in the _main-local.php_, change the **Module::FORMAT...** entry to **\kartik\datecontrol\Module::FORMAT...** 

```
return [
 'modules' => [
        'datecontrol' => [
            'class' => 'kartik\datecontrol\Module',
            // format settings for displaying each date attribute (ICU format example)
            'displaySettings' => [
                \kartik\datecontrol\Module::FORMAT_DATE => 'dd-MM-yyyy',
                \kartik\datecontrol\Module::FORMAT_TIME => 'HH:mm:ss a',
                \kartik\datecontrol\Module::FORMAT_DATETIME => 'dd-MM-yyyy HH:mm:ss a',
            ],
[...]
```
I think, this should solve the above problems.
