### ISSUE TITLE
shader file selected dates with filed range.

### ISSUE THREAD

**Issue by tecnologiaterabyte** [kartik-v/yii2-datecontrol#47]
Hi kartikv, its posible activate shading FieldRange :: widget With DateControl, as is done FieldRange :: INPUT_DATE,

Example Image:

![example_date_control](https://cloud.githubusercontent.com/assets/4957021/6251628/330b07ec-b767-11e4-8997-fb6f24c61640.png)

Thks,

**Comment by kartik-v** [comment]
Not currently possible or implemented because its a special feature of the datepicker plugin which I had tweaked to work with Yii active form validation using dual input fields. Datecontrol by default understands asingle input and not dual. Will check later when I get time.
