### ISSUE TITLE
Configuring yii2-dateControl with yii2-widget-datepicker.

### ISSUE THREAD

**Issue by tecnologiaterabyte** [kartik-v/yii2-datecontrol#48]
Hi Kartikv sorry to bother you again, I have the following questions, I set DateControl with yii2-widget-datepicker, as he was passing parameters to display and save data.

My Config:

    'modules' => [
        // Configuracion de Horas y Fechas.
        'datecontrol' =>  [
            'class' => 'kartik\datecontrol\Module',

            // format settings for displaying each date attribute (ICU format example)
            'displaySettings' => [
                kartik\datecontrol\Module::FORMAT_DATE => 'dd-MM-yyyy',
                kartik\datecontrol\Module::FORMAT_TIME => 'HH:mm',
                kartik\datecontrol\Module::FORMAT_DATETIME => 'dd-MM-yyyy HH:mm:ss a',
            ],

            // format settings for saving each date attribute (PHP format example)
            'saveSettings' => [
                kartik\datecontrol\Module::FORMAT_DATE => 'php:U', // saves as unix timestamp
                kartik\datecontrol\Module::FORMAT_TIME => 'php:H:i',
                kartik\datecontrol\Module::FORMAT_DATETIME => 'php:Y-m-d H:i:s',
            ],

            // set your display timezone
            'displayTimezone' => 'America/Caracas',

            // set your timezone for date saved to db
            'saveTimezone' => 'America/Caracas',

            // automatically use kartik\widgets for each of the above formats
            'autoWidget' => true,

            // default settings for each widget from kartik\widgets used when autoWidget is true
            'autoWidgetSettings' => [
                kartik\datecontrol\Module::FORMAT_DATE => ['type'=>1, 'pluginOptions'=>['autoclose'=>true]], // example
            ],
        ],

Example FileRange with Datepicker:

    echo kartik\field\FieldRange::widget([
        'form' => $form,
        'model' => $model,
        'label' => 'Seleccione Duración del Horario',
        'attribute1' => 'Turn003',
        'attribute2' => 'Turn004',
        'useAddons' => false,
        'type' => kartik\field\FieldRange::INPUT_DATE,
    ]);

As you can pass yii2-widgets-datepicker the display format parameters and save format, is this possible,

Thks,

**Comment by kartik-v** [comment]
It will not work because DateControl mirrors a duplicate input for saving... and it will only do it for one input but the FieldRange has two inputs... so there will be a mismatch.

As I said in another discussion, this will need some enhancement and not straightforward.

You can use two different DateControl fields with DatePicker to create a range currently. I will update on this when I get time if I can support FieldRange.

**Comment by kartik-v** [comment]
I have created an enhancement request #49 and will handle this once I get time.

**Comment by tecnologiaterabyte** [comment]
Thks Kartikv.
