### ISSUE TITLE
The format of <field> is invalid

### ISSUE THREAD

**Issue by LarryTX** [kartik-v/yii2-datecontrol#53]
I've tried to set up the Date Control exactly as described in your documentation, and no matter what I do, I get the error message, "The format of Purchase Date is invalid." I'm hoping you can point to what I'm doing wrong.

In my backend/config/main.php, in the 'modules' section, I've got this:
```php
'datecontrol' => [
                'class' => 'kartik\datecontrol\Module',

                // format settings for displaying each date attribute (ICU format example)
                'displaySettings' => [
                    Module::FORMAT_DATE => 'dd-MM-yyyy',
                    Module::FORMAT_TIME => 'HH:mm:ss ',
                    Module::FORMAT_DATETIME => 'dd-MM-yyyy HH:mm:ss a',
                ],
                // format settings for saving each date attribute (PHP format example)
                'saveSettings' => [
                    Module::FORMAT_DATE => 'php:U', // saves as unix timestamp
                    Module::FORMAT_TIME => 'php:H:i:s',
                    Module::FORMAT_DATETIME => 'php:Y-m-d H:i:s',
                ],

                // set your display timezone
                // 'displayTimezone' => 'Asia/Kolkata',

                // set your timezone for date saved to db
                'saveTimezone' => 'UTC',
                // automatically use kartik\widgets for each of the above formats
                'autoWidget' => true,

            ],
```
And in _form.php, my field is configured like this:
```php
<?=
                        $form->field($model, 'purchase_date')->widget(DateControl::classname(), [
                            'type'           => DateControl::FORMAT_DATE,
                            // 'ajaxConversion' => true,
                            'options'        => [
                                'pluginOptions' => [
                                    'autoclose' => true
                                ]
                            ]
                        ]
                        );
                    ?>
```
The DatePicker displays in the form, but when I select a date from it (not entering the date manually) and attempt to save, I get this:
![datepicker error](https://cloud.githubusercontent.com/assets/20743/6861814/b9015c42-d40a-11e4-9dc9-b94b59a5f8fd.jpg)
Can you help identify what I'm doing wrong?

**Comment by kartik-v** [comment]
Check if you have setup any model validation rule for `purchase_date` and remove the same and try. 

If you are using timezone you must set `ajaxConversion` as `true`

**Comment by LarryTX** [comment]
Actually, I have tried it both ways. With the following rule, I get the invalid date format error:
```php
[['purchase_date', 'expiration_date', 'renewal_date'], 'date'],
```
With no rule and with a "safe" rule (separate trials), I don't get an error message. It just doesn't store the date. I end up with 0000-00-00 in the DB table. (The default for the table column is set to NULL, so apparently, it overrides the default. MySQL database.) I've tried it with ```'ajaxConversion' => true,```, and that doesn't seem to change anything. It still stores the date as 0000-00-00.

**Comment by kartik-v** [comment]
- As I guessed, your primary issue was the invalid date format error which is caused because you are using yii date validation rule in your model and the date format you specified in the validation rule is different than what is actually generated. 
- the second part of the problem which you have now stated is date format not generating correct. You need to debug this - DateControl widget relies entirely on your `displayFormat` and `saveFormat` - to convert dates between display and save. If any of the data do not match these formats exactly - you will get a format conversion error. You may first try setting these formats at the widget level and then check via debug messages (JS alerts) if the data you are passing to the widget is in exactly the right format.

**Comment by LarryTX** [comment]
Thanks. Interestingly, I had converted the displaySettings and saveSettings in config/main.php to the php: format, and that still didn't work. So, from what you said, I simply copied and pasted those formats from config/main.php to the saveFormat and displayFormat settings in the widget, and it worked beautifully. No changes whatsoever to the format, just a simple copy and paste. Guess now I've learned not to bother with the config settings and rely only on the widget.

**Comment by kartik-v** [comment]
You must read the [docs for the DateControl defaulting rules](http://demos.krajee.com/datecontrol#defaults). For example Its in this order (e.g. displayFormat)

-  if `displayFormat` is set in DateControl widget, it will be first used and override everything else
- else if nothing is available at widget level and Yii::$app->params['dateControlDisplay'] is set, it will be next used ... this will override any other setting
- else, the format as set in Module::displaySettings will be used from the DateControl Module
- else, the format as set in Yii::$app->formatter will be used

You may be having the params set to a different format which may be causing the error.

**Comment by LarryTX** [comment]
Actually, I have read the docs for DateControl defaulting rules ---- many, many, many, many times. In fact, I always read as much documentation as I can find before I even start.

And no. I'm sorry, but there are no datecontrol params or even anything to do with date formats at all in:
* backend\config\params.php
* backend\config\params-local.php
* backend\config\main.php, 'params' key
* backend\config\main-local.php, 'params' key
* common\config\params.php
* common\config\params-local.php
* common\config\main.php, 'params' key
* common\config\main-local.php, 'params' key

I very much appreciate the excellent extensions that you produce and your assistance.

**Comment by kartik-v** [comment]
Strange ... anyway in that case it means its not able to read your module settings or there's something amiss in your environment. Just to ensure that its not something missed in the extension - can you confirm the following:

- do you have the latest version of the package and all classes exactly as in `dev-master` 
- for debugging purpose to note if its something in your environment OR something to improve in the extension... it may help if you can just put some debug messages within the `DateControl::run()` method to note what is the displayFormat and saveFormat generated when you do not set these at the widget level.

**Comment by kartik-v** [comment]
Strange ... anyway in that case it means its not able to read your module settings or there's something amiss in your environment. Just to ensure that its not something missed in the extension - can you confirm the following:

- do you have the latest version of the package and all classes exactly as in `dev-master` 
- for debugging purpose to note if its something in your environment OR something to improve in the extension... it may help if you can just put some debug messages within the `DateControl::run()` method to note what is the displayFormat and saveFormat generated when you do not set these at the widget level.

Or you can create a simple extended class like this and let know:

```
class TestDateControl extends \kartik\datecontrol\DateControl
{
    public function run() {
        parent::run();
        echo '<h4>Display Format: '. $this->displayFormat . '</h4>';
        echo '<h4>Save Format: '. $this->saveFormat . '</h4>';
    }
}
```

Then use the TestDateControl to render your widget and let know.
