### ISSUE TITLE
Time value in datetime fiels is not writed in db

### ISSUE THREAD

**Issue by eugenyho** [kartik-v/yii2-datecontrol#57]
It is strange:

my config (myapp/common/config/main.app):
<?php
use \kartik\datecontrol\Module;
return [
    'language' => 'ru-RU',
    'vendorPath' => dirname(dirname(**DIR**)) . '/vendor',
    'components' => [
         'i18n' => [
              'translations' => [
              'frontend_' => [
                        'class' => 'yii\i18n\PhpMessageSource',
                        'basePath' => '@common/messages',
                             ],
              'backend_' => [
                        'class' => 'yii\i18n\PhpMessageSource',
                        'basePath' => '@common/messages',
                            ],
                                ],
                   ],
        'cache' => [
            'class' => 'yii\caching\FileCache',
        ],
        'user' => [
            'class' => 'amnah\yii2\user\components\User',
        ],
    ],

```
'modules' => [
    'user' => [
        'class' => 'amnah\yii2\user\Module',
              ],
    'gridview' =>  [
        'class' => 'kartik\grid\Module',
                   ],

    'datecontrol' =>  [
        'class' => 'kartik\datecontrol\Module',
        'displaySettings' => [Module::FORMAT_DATE     => 'd.m.Y',
                              Module::FORMAT_TIME     => 'H:i:s',
                              Module::FORMAT_DATETIME => 'dd.MM.yyyy HH:mm'],
        'displayTimezone' => 'Asia/Almaty',

        'saveSettings' => [Module::FORMAT_DATE => 'php:U', // saves as unix timestamp
                           Module::FORMAT_TIME => 'php:H:i:s',
                           Module::FORMAT_DATETIME => 'php:Y-m-d H:i:s'],
        'saveTimezone' => 'Asia/Almaty',
                      ],
           ],
```

];

my _form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\widgets\DateTimePicker;
use kartik\datecontrol\DateControl;
?>

<div class="coldcontact-form">
    <?php $form = ActiveForm::begin(); ?>
....
    <?php // $form->field($model, 'lasttalk') ?>
    <?= $form->field($model, 'lasttalk')->widget(DateControl::classname(),.
                                          ['type' => DateControl::FORMAT_DATETIME]) ?>
...
<?php ActiveForm::end(); ?>
</div>

In this configuration, date part saved correct, but time part saved as "00:00:00" everytime.

What wrong?

**Comment by alexander-suter** [comment]
I know why.

In your async request you don't pass the type.
vType in datecontrol.js is empty. The vType will not be passed to ParseController. If it is not passed, then it will automaticly take the DATE as format.
At the moment I don't know how to fix that...
