### ISSUE TITLE
Probably bug re triggering of change event in datecontrol.js

### ISSUE THREAD

**Issue by andrewblake1** [kartik-v/yii2-datecontrol#58]
When using asynchronous $.ajax the success function that alters the value of $idSave on line 73 is being called after the call to trigger the change event on line 91 resulting in the change event not having access to the new value - because of its asynchronous-ness :) 

To fix I suggest putting $idSave.trigger('change'); following $idSave.val() calls on line 55 and 73 in the current code (instead of line 91 after the call to validate).

Note this fix also resolves an issue with on change being called three times for save input instead of once - didn't trace thru to find why. I havn't tested any other scenarios other than my own use so haven't created a PR but can if you like - in other.

Hope I have this right and am not wasting your time.

**Comment by kartik-v** [comment]
Resolved via latest commit.
