### ISSUE TITLE
Remove bootstrap as a requirement.

### ISSUE THREAD

**Issue by PommeVerte** [kartik-v/yii2-datecontrol#61]
Hey,

This system is really nice. There is however one issue for us. It automatically loads bootstrap which completely breaks our layout. 
I can understand how this is a requirement if using your own datepicker widgets but in the event of custom datepicker widgets in systems that don't use bootstrap it's a deal breaker. Isn't bootstrap already a dependency for your widgets? Maybe we can remove the fact that datecontrol assets depend on `base\AssetBundle` . I'm willing to make a pull request if I get the ok.

**Comment by PommeVerte** [comment]
For those who may run into this issue, the workaround is to add the following component to your configuration file:

```php

		'assetManager' => [
            'bundles' => [
                'yii\bootstrap\BootstrapAsset' => [
                    'sourcePath' => null,   // do not publish the bundle
                    'css' => [
                    ],

                ],
            ],
        ],
```

**Comment by kartik-v** [comment]
Yes Yii asset manager is to be used like above for such cases.
