### ISSUE TITLE
Possible 'class' option bug in autoWidgetSettings

### ISSUE THREAD

**Issue by andrewblake1** [kartik-v/yii2-datecontrol#63]
Havn't delved too deep into the reason for this as found a simple way around it.

In module setup autoWidgetSettings I expected to be able to use 'class' to set the class of the widget similar to Demo > Usage > WidgetSettings > Module::FORMAT_DATE > 'class'.

I havn't tried setting autoWidget to off to see if it works there, but it doesn't seem to in autoWidgetSettings which I would have thought to contain the same settings (without close examination).

I suspect the setting may be incorrectly documented in the demo and perhaps should be widgetClass as strangely my simple way around is just to define it in my DateControl extended class using widgetClass - puzzled as to why it didn't work in module setup as widgetClass or class but the workaround gets me operable so really just a minor bug - but I think probably a bug. Apologies for not taking the time to step thru.

IMHO
The time picker plugin currently used has produced numerous issues for me. Friends haven't found it particularly intuitive. Its been a while but I think when I tried to use it as a gridview filter it may have triggered a search with every minor spin change due to the change event being triggered every time as opposed to on blur (apologies if I am incorrect on this - just going by memory).

FYI in case useful to suggest to anyone else with the above issues:
for a TimePicker I am now using DateTimePicker as below 
```
[
    'type' => 1,                // no icons
    'pluginOptions' => [
        'startView' => 'day',   // start from hour view - what plugin author refers to as day view
        'autoclose' => true,    // close after last selection
        'format' => 'HH:mm',
    ],
    'pluginEvents' => [
        'show' => 'function(e) {$(".datetimepicker").addClass("timepicker");}',
        'hide' => 'function(e) {$(".datetimepicker").removeClass("timepicker");}',
    ],
],
```
with css
```
/* to allow datetime picker to be used just as a time picker */
.timepicker .datetimepicker-hours thead, .timepicker .datetimepicker-minutes .switch {
    display: none;
}

.timepicker .datetimepicker-hours table, .timepicker .datetimepicker-minutes table {
    width: 193px;
}
```

Cheers again for the awesome extensions

**Comment by kartik-v** [comment]
You may want to [read docs](http://demos.krajee.com/datecontrol). You need to check widgetSettings in Module. Autowidget is only for using preset krajee extension classes.

**Comment by andrewblake1** [comment]
Yip, you are correct of course - couldn’t be more obvious now - apologies for taking up your time. Docs are clear, it makes sense and works perfectly - not sure what I was thinking.
