### ISSUE TITLE
Problem with two DateControls on the same page

### ISSUE THREAD

**Issue by sergiocastelani** [kartik-v/yii2-datecontrol#67]
When I put two date controls on the same page, using a code like:

```php
echo $form->field($model, 'attribute1')
    ->widget(DateControl::classname(),['type' => DateControl::FORMAT_DATE]);

echo $form->field($model, 'attribute2')
    ->widget(DateControl::classname(),['type' => DateControl::FORMAT_DATE]);
```

The second widget is initialized with {... "dateSettings": true,  ...}, but "dateSettings" should be that array with the language labels for days, months and meridiem.

I could solve this by changing the line at DateControl::setLocate() with:
```php
 $this->pluginOptions['dateSettings'] = require_once($file);
```

to

```php
 $this->pluginOptions['dateSettings'] = require($file);
```

**Comment by kartik-v** [comment]
This cannot be reproduced... datecontrol widgets with multiple languages seem to work fine.
