### ISSUE TITLE
datecontrol/parse/convert ajax triggering validation before any user action

### ISSUE THREAD

**Issue by derekisbusy** [kartik-v/yii2-datecontrol#70]
The datecontrol/parse/convert ajax calls are triggering the form to validate on page load. Is there a way to prevent this besides removing the validation rules in the model?

**Comment by kartik-v** [comment]
No this is not correct - you may need to check your code if you are somehow triggering change of the displayed fields.

The form validation will not be triggered unless you have the input fields itself triggering a change.
