### ISSUE TITLE
What's that?

### ISSUE THREAD

**Issue by serhatozles** [kartik-v/yii2-datecontrol#75]
@kartik-v Date control is sending a data on ajax.
## Address: 

http://examplesite.com/datecontrol/parse/convert
## Datas:

displayDate=31/08/2015
type=date
dispFormat=d/m/Y
saveFormat=Y-m-d
dispTimezone=Europe/Istanbul
saveTimezone=UTC
settings[days][]=Pazar
...
## RETURNING:

status:"success"
output:"2015-08-30" <==== ? I can't understand that is returning to me -1 day.

``` php
$date = DateControl::getTimestamp($post['displayDate'], $dispFormat, $dispTimezone, $settings);
print_r($date);
```
## Result:

```
DateTime Object
(
    [date] => 2015-08-30 21:00:00
    [timezone_type] => 3
    [timezone] => UTC
)
```

---

and i have another question. How can i use that in this extension? Two different date picker. Can you give me an example?

``` javascript
            $('#startdate').datepicker({
                dateFormat : 'dd.mm.yy',
                prevText : '<i class="fa fa-chevron-left"></i>',
                nextText : '<i class="fa fa-chevron-right"></i>',
                onSelect : function(selectedDate) {
                    $('#finishdate').datepicker('option', 'minDate', selectedDate);
                }
            });

            $('#finishdate').datepicker({
                dateFormat : 'dd.mm.yy',
                prevText : '<i class="fa fa-chevron-left"></i>',
                nextText : '<i class="fa fa-chevron-right"></i>',
                onSelect : function(selectedDate) {
                    $('#startdate').datepicker('option', 'maxDate', selectedDate);
                }
            });
```

**Comment by Enrica-r** [comment]
Your fist issue: this has to do with UTC conversion. see issue #96 there you can find details and the solution.

In your script you use datepicker from bootstrap directly. You should use Kartik's widget 'datepicker' with or without Datecontrol. With Kartik's datepicker you can define a plugin-Event function which could handle your min and max date. If you combine Datecontrol and your calls you will have conflicts.

**Comment by kartik-v** [comment]
I am closing this issue as there will be updates via #92 and #96.
