### ISSUE TITLE
kartik datecontrol is not setting the date if a date of  tuesday and thursday is selected

### ISSUE THREAD

**Issue by MagSag** [kartik-v/yii2-datecontrol#82]
When I select a date that is on tuesday or thursday the hidden input value is becoming false; so when I send it to server to be validate it is not valide

**Comment by MagSag** [comment]
please  I need your help to understand what is wrong.

**Comment by kartik-v** [comment]
You need to debug your server code to see what values are getting passed?

Also check your widget and module configuration, check your date formats, timezone setup (if using timezones) and then see if the data is getting passed right.

Your use case cannot be reproduced. You can [cross check with the demos page](http://demos.krajee.com/datecontrol-demo) and see that all dates and days (incl Tue/Thu) work well.

**Comment by MagSag** [comment]
Here is my configuration 
```

'datecontrol' =>  [
        'class' => 'kartik\datecontrol\Module',
 
        // format settings for displaying each date attribute (ICU format example)
        'displaySettings' => [
            Module::FORMAT_DATE => 'php:D d-M-Y',
            Module::FORMAT_TIME => 'php:H:i:s',
            Module::FORMAT_DATETIME => 'php:D d-M-Y H:i:s', 
        ],
        
        // format settings for saving each date attribute (PHP format example)
        'saveSettings' => [
            Module::FORMAT_DATE => 'php:Y-m-d', 
            Module::FORMAT_TIME => 'php:H:i:s',
            Module::FORMAT_DATETIME => 'php:Y-m-d H:i:s',
        ],
 
        // set your display timezone
//        'displayTimezone' => 'Asia/Kolkata',
 
        // set your timezone for date saved to db
//        'saveTimezone' => 'UTC',
        
        // automatically use kartik\widgets for each of the above formats
        'autoWidget' => true,
 
        // default settings for each widget from kartik\widgets used when autoWidget is true
        'autoWidgetSettings' => [
            Module::FORMAT_DATE => ['type'=>2, 'pluginOptions'=>['autoclose'=>true]], // example
            Module::FORMAT_DATETIME => [], // setup if needed
            Module::FORMAT_TIME => [], // setup if needed
        ],
        
        // custom widget settings that will be used to render the date input instead of kartik\widgets,
        // this will be used when autoWidget is set to false at module or widget level.
        'widgetSettings' => [
            Module::FORMAT_DATE => [
                'class' => 'yii\jui\DatePicker', // example
                'options' => [
                    'dateFormat' => 'php:d-M-Y',
                    'options' => ['class'=>'form-control'],
                ]
            ]
        ]
        // other settings
    ]
```

and in my view :    ```
<?=$form->field($model, 'dated')->widget(DateControl::classname(), [
    'type'=>DateControl::FORMAT_DATE,
    'language'=>Yii::$app->language,
    'ajaxConversion'=>false,
    'options' => [
        'pluginOptions' => [
            'autoclose' => true
        ]
    ]
])?>
```
So is there any mistake?

**Comment by kartik-v** [comment]
Not sure as I mentioned you may need to debug...

Have you also tried with `'ajaxConversion' => true`

**Comment by MagSag** [comment]
I tried setting 'ajaxConversion' => true it just adding the attribute value without any value to the hidden field. so nothing is working I don't really get where the problem is; I follow all step of configuration

**Comment by MagSag** [comment]
It is working now, What I did is ;
I Enable timezone setting in web.php config fie
```
'displayTimezone' => 'UTC', 
 'saveTimezone' => 'UTC', 
```
and set
` 'ajaxConversion'=>true,
`
so As Mysql does not convert the date and time datatype data to client timezone; I hope date will not influenced by the timezone when being displayed. The only problem is I use Yii::$app->formatter->asDate() which when formatting influence the date by the timezone.

Thanks!!!

**Comment by alvarolordelo** [comment]
I would like to pass the argument required to client side validation.
 'data_fim' => [
                'label' => 'Data de Fim:',
                'type' => TabularForm::INPUT_WIDGET,
                'widgetClass' => \kartik\datecontrol\DateControl::classname(),
                'columnOptions' => ['width' => '200px'],
                'options' => [
                    'required' => 'required',
                ],
                'options' => [
                    'type' => \kartik\datecontrol\DateControl::FORMAT_DATE,
                    'saveFormat' => 'php:Y-m-d',
                    'ajaxConversion' => true,
                    'options' => [
                        'required' => 'required',
                        'pluginOptions' => [
                            'required' => 'required',
                            'placeholder' => 'Choose Data Fim',
                            'autoclose' => true
                        ]
                    ],
                ]
            ],
it isn't working ... the client side isn't getting the required in the input field .
I'm using tabular form
 use kartik\builder\TabularForm;
