### ISSUE TITLE
In parseMarkup the size is evaluated but not applied

### ISSUE THREAD

**Issue by d4rkstar** [kartik-v/yii2-datecontrol#87]
Hello Kartik!
it seems that in parseMarkup, when type is TYPE_INPUT,  the size is evaluated but can't be applied because the $input It has already been transformed into html

![schermata 2016-03-26 alle 08 25 13](https://cloud.githubusercontent.com/assets/4957015/14058800/ba1bca30-f32c-11e5-949b-e49f5241519a.png)

Check the attached screenshot with a xdebug session. At row 198 the new css class is built, but at row 199 it can't be applied.

Maybe this case should be managed in the renderInput (at row 141) ?

Bruno

**Comment by d4rkstar** [comment]
Hello,
i noticed right now that in case the type is TYPE_INPUT, the size of the widget is managed with the filterInputOptions class. This should be addressed better in the docs.

Example:
`
'filterInputOptions'=>[
  'class'=>'form-control-xs',
],
`

Bruno

**Comment by kartik-v** [comment]
This is not related to this extension.

I see that configuration above you have mentioned is for the `DataColumn` in `yii2-grid` extension (so you should look into the documentation for `yii2-grid`).

`filterInputOptions` is for setting attributes for one of the HTML inputs rendered (e.g. input, dropdownList, checkbox etc.)

`filterWidgetOptions` is for setting widget options if using one of the input widgets.

**Comment by d4rkstar** [comment]
Hello, i still think that - however - that addCssClass at row 198 is useless... the class is added but not used by input!
