### ISSUE TITLE
Saving wrong date when display timezone is differnet than savetimezone

### ISSUE THREAD

**Issue by bobonov** [kartik-v/yii2-datecontrol#88]
/datecontrol/parse/convert checking date take in consideration the timezone so, for example when  dispaly time zone is set to Europe/Rome and save timezone is set to UTC, the saved date  result in 1 day before.
these are the post parameter of the ajax request to 
/datecontrol/parse/convert
```
dispFormat=d-m-Y
dispTimezone=Europe/Rome
displayDate=18-10-2011
saveFormat=Y-m-d
saveTimezone=UTC
```
and this is the json answer
```json
{"status":"success","output":"2011-10-17"}
```
I think timezone should not be taken in account when handling date (without time)

**Comment by kartik-v** [comment]
No it would be inconsistent for genuine validation of dates (a date usually is treated as datetime with 00:00:00 as the time part).

If you need the conversion to be prevented... set the `displayTimezone` and `saveTimezone` to same in your DateControl widget level configuration.
