### ISSUE TITLE
Kartik datecontrol is not working when the local is french

### ISSUE THREAD

**Issue by MagSag** [kartik-v/yii2-datecontrol#90]
When the language is english everything is working well but when the language is french the day short form displayed is being with a dot which is making the date to not be valid when send to the server. In English the shortformat of day is: Tuesday = Tue In French the shortform is: Mardi= mar but instead of displaying mar when the user select a date it is displaying mar. 4 Mai 2016.

Here is the configuration I did :

```
'datecontrol' =>  [
        'class' => 'kartik\datecontrol\Module',

        // format settings for displaying each date attribute (ICU format example)
        'displaySettings' => [
            Module::FORMAT_DATE => 'php:D d-M-Y',
            Module::FORMAT_TIME => 'php:H:i:s',
            Module::FORMAT_DATETIME => 'php:D d-M-Y H:i:s', 
        ],

        // format settings for saving each date attribute (PHP format example)
        'saveSettings' => [
            Module::FORMAT_DATE => 'php:Y-m-d', 
            Module::FORMAT_TIME => 'php:H:i:s',
            Module::FORMAT_DATETIME => 'php:Y-m-d H:i:s',
        ],

//         set your display timezone
        'displayTimezone' => 'UTC',

//         set your timezone for date saved to db
        'saveTimezone' => 'UTC',

        // automatically use kartik\widgets for each of the above formats
        'autoWidget' => true,

        // default settings for each widget from kartik\widgets used when autoWidget is true
        'autoWidgetSettings' => [
            Module::FORMAT_DATE => ['type'=>2, 'pluginOptions'=>['autoclose'=>true]], // example
            Module::FORMAT_DATETIME => [], // setup if needed
            Module::FORMAT_TIME => [], // setup if needed
        ],

        // custom widget settings that will be used to render the date input instead of kartik\widgets,
        // this will be used when autoWidget is set to false at module or widget level.
        'widgetSettings' => [
            Module::FORMAT_DATE => [
                'class' => 'yii\jui\DatePicker', // example
                'options' => [
                    'dateFormat' => 'php:d-M-Y',
                    'options' => ['class'=>'form-control'],
                ]
            ]
        ]
```

In the view I have:

```
<?=$form->field($model, 'dated')->widget(DateControl::classname(), [
    'type'=>DateControl::FORMAT_DATE,
    'language'=>Yii::$app->language,
    'ajaxConversion'=>true,
    'options' => [
        'pluginOptions' => [
            'autoclose' => true
        ]
    ]
])?>
```

Trying to debug the code the what I found is;  if I remove the dot I added everything is working fine for french but if I don't the date is invalid. I try also to see from where that dot was being added for french but could not see!! 
Here is the code that I modify in Parsecontroller.php line 37 by removing dot:  
`$date = DateControl::getTimestamp(preg_replace('/\./','',$post['displayDate']), $dispFormat, $dispTimezone, $settings);`

**Comment by MagSag** [comment]
And also the other problem is; if the jun, jan, feb,march,july,august, month is select jun (juin) the `$source` value is containing junn instead of jun after replacement in the Datecontrol\parseLocal
`$source = str_ireplace($settings[$key], $value, $source); //is the line `
And I've noticed it is because the value displayed is different from the value in settings array.
Ex: ven. 12-juin.-2016 displayed yet the short month is jui in settings array; so the replacement is just changing jui from juin leaving n which makes the month juun after replacement. Settings array values should be reviewed to correspond to displayed for shortmonth and also from the displayvalue array dot should be remove.

**Comment by kartik-v** [comment]
The parsing is done based on locale dateSettings which is a part of the locales folder in this extension repo. For example you need to cross check what you are saying in [the French Locale setting](https://github.com/kartik-v/yii2-datecontrol/blob/master/locales/fr/dateSettings.php) and ensure your data matches the french locales for `monthsShort` and `monthsLong`.
