### ISSUE TITLE
Getting current value of input field in change event

### ISSUE THREAD

**Issue by lupoalberto** [kartik-v/yii2-datecontrol#91]
Hi

I'm trying to get the value of the following form field via javascript:

> ```
>         <?= $form->field($model, 'datetime')->widget(DateControl::classname(), [
>             'type'=>DateControl::FORMAT_DATETIME,
>             // Display in locale's date format:
>             'displayFormat' => \yii::$app->formatter->datetimeFormat,
>             'options' => [
>                 'id' => '_date',
>                 'pluginOptions' => [
>                     'autoclose' => true,
>                 ]
>             ],
>             'pluginEvents' => [
>                 "change" => "function(){
>                     alert($('#_date').val());
>                 }",
>             ]
>         ]); ?>
> ```

in this simple example I just try to put the value out if the field value changes. If I try to change the date for example, I only get an empty alert box. If I change it again, the "old" value is displayed.

**Comment by Enrica-r** [comment]
Datecontrol itself hasn't pluginEvents. Datecontrol wraps the widget `datePicker` to handle the different format between display and saving on view level. This is done by two different form fields.

The display field is visible and it contains the `datePicker`widget. The save-field is hidden. If your field id is '_date' then this is the save-field which is used in controller and model. The field which has probably the pluginEvent has the extension '-disp'. So in your case use `alert($('#_date-disp').val();`

**Comment by kartik-v** [comment]
Currently plugin events are available for datecontrol as well (refer enhancement #92).
