### ISSUE TITLE
Issue in Display Date

### ISSUE THREAD

**Issue by sahilpatel2216** [kartik-v/yii2-datecontrol#95]
Hello,

Datetime format in saveSettings works properly but issue in display date if i update then display datetime as per my format but view and index file in date are not display as per my format.

give solution

**Comment by Enrica-r** [comment]
This format of files `index.php` and `view.php` aren't formatted by Datecontrol. I excpect this is done by Yii->formatter. Please post a code fragment of index or view file.

If you have set Datecontrol's `displayFormat` in Datecontrol module config or in Datecontrol widget call this has impact for Datecontrol only. I expect that you don't have set Yii formatter to same format.

I personally don't set `displayFormat` I set the correct language code in my config file eg. `'language' => 'de-CH',`. This sets the correct country format in Yii formatter and there in Datecontrol also. Datecontrol takes Yii's formatter format per default.
