### ISSUE TITLE
POST /datecontrol/parse/convert 404 (Not Found)

### ISSUE THREAD

**Issue by mystadio** [kartik-v/yii2-datecontrol#99]
It seems the module doesn't prepend its convert route to the UrlManager's rules.

Here is the ugly fix I did to make it work:

``` php
'urlManager' => [
    'class' => 'yii\web\UrlManager',
    'enablePrettyUrl' => true,
    'enableStrictParsing' => true,
    'showScriptName' => false,
    'rules' => [
        // Fix for datetimepicker
        'POST datecontrol/parse/convert' => 'datecontrol/parse/convert',

        // Other rules
    ],
],
```

I tried adding the yii\base\BootstrapInterface to the module without success.

**Comment by mystadio** [comment]
I also searched were you are referencing `$convertAction` and it's only used in the `$.ajax` options. I couldn't find any references from the parent classes as well.

**Comment by manoelt** [comment]
Same here.

**Comment by igokul1973** [comment]
Same here.

**Comment by sankaest** [comment]
Was it solved somehow?

**Comment by MoVoDesign** [comment]
Back to the same problem it seems

**Comment by CheckeredFlag** [comment]
@kartik-v any chance this can be addressed by updating the UrlManager rules accordingly?
